const ENTER_ADD_TASK = "ENTER_ADD_TASK";
const EXIT_ADD_TASK = "EXIT_ADD_TASK";
const CREATE_NEW_TASK = "CREATE_NEW_TASK";
const SWIPED_ALL_REMINDERS = "SWIPED_ALL_REMINDERS";

export { ENTER_ADD_TASK, EXIT_ADD_TASK, CREATE_NEW_TASK, SWIPED_ALL_REMINDERS };
