const ENTER_ADD_TASK = "ENTER_ADD_TASK";
const EXIT_ADD_TASK = "EXIT_ADD_TASK";
const CREATE_NEW_TASK = "CREATE_NEW_TASK";
const SWIPED_ALL_REMINDERS = "SWIPED_ALL_REMINDERS";
const PROJECT_TYPE_CLICKED = "PROJECT_TYPE_CLICKED";

export {
  ENTER_ADD_TASK,
  EXIT_ADD_TASK,
  CREATE_NEW_TASK,
  SWIPED_ALL_REMINDERS,
  PROJECT_TYPE_CLICKED
};
